[accounts.Rutgers]
root_mailbox = '[Gmail]'
format = "imap"
server_hostname='imap.gmail.com'
#server_password="password"
server_password_command="pass gmail/rutgers"
server_username="hl1276@scarletmail.rutgers.edu"
server_port="993"
listing.index_style = "threaded"
identity = "haoyu.li@rutgers.edu"
display_name = "HAOYU LI"
## match every mailbox:
subscribed_mailboxes = ["*" ]
#composing.send_mail = 'msmtp --read-recipients --read-envelope-from'
composing.send_mail = { hostname = "smtp.gmail.com", port = 587, auth = { type = "auto", username = "hl1276@scarletmail.rutgers.edu", password = { type = "command_eval", value = "pass gmail/rutgers" } }, security = { type = "STARTTLS" } }
## Gmail auto saves sent mail to Sent folder, so don't duplicate the effort:
composing.store_sent_mail = false
